export default function handler(req, res) {
    res.status(200).json({
        "liked": false,
        "tags": ["houdini", "FX", "fire"],
        "hide_as_adult": false,
        "visible_on_artstation": true,
        "assets": [{
            "has_image": false,
            "has_embedded_player": false,
            "player_embedded": null,
            "oembed": null,
            "id": 35921151,
            "title": null,
            "title_formatted": "",
            "image_url": "https://cdnb.artstation.com/p/assets/covers/images/035/921/151/large/gilles-avraam-gilles-avraam-post1-insta-00-00-03-00-still001.jpg?1616258688",
            "width": 1080,
            "height": 1080,
            "position": 0,
            "asset_type": "cover",
            "viewport_constraint_type": "constrained"
        }, {
            "has_image": true,
            "has_embedded_player": true,
            "player_embedded": "<iframe src='https://www.artstation.com/api/v2/animation/video_clips/e4979969-0ad1-412c-8d3a-6e5e02e2a360/embed.html' width='1920' height='1080' frameborder='0' allowfullscreen allows='autoplay; fullscreen' style='max-width: 1920px; max-height: 1080px;'></iframe>",
            "oembed": {"width": 1920, "height": 1080, "provider_name": "ArtStation"},
            "id": 35921044,
            "title": "Logo animation",
            "title_formatted": "<div class=\"asset-caption\"><p>Logo animation</p></div>",
            "image_url": "https://cdna.artstation.com/p/assets/video_clips/images/035/921/044/large/gilles-avraam-thumb.jpg?1616258309",
            "width": 1920,
            "height": 1080,
            "position": null,
            "asset_type": "video_clip",
            "viewport_constraint_type": "constrained"
        }, {
            "has_image": true,
            "has_embedded_player": true,
            "player_embedded": "<iframe src='https://www.artstation.com/api/v2/animation/video_clips/95077279-69e8-4b07-b3c5-efdbd8a67235/embed.html' width='1920' height='1080' frameborder='0' allowfullscreen allows='autoplay; fullscreen' style='max-width: 1920px; max-height: 1080px;'></iframe>",
            "oembed": {"width": 1920, "height": 1080, "provider_name": "ArtStation"},
            "id": 35921050,
            "title": "fire alone",
            "title_formatted": "<div class=\"asset-caption\"><p>fire alone</p></div>",
            "image_url": "https://cdna.artstation.com/p/assets/video_clips/images/035/921/050/large/gilles-avraam-thumb.jpg?1616258381",
            "width": 1920,
            "height": 1080,
            "position": null,
            "asset_type": "video_clip",
            "viewport_constraint_type": "constrained"
        }],
        "collections": [],
        "user": {
            "followed": false,
            "following_back": false,
            "blocked": false,
            "is_staff": false,
            "is_plus_member": false,
            "is_organization_owner": false,
            "id": 2685317,
            "username": "gillesavraam",
            "headline": "Futur technical director FX",
            "full_name": "Avgilles",
            "permalink": "https://www.artstation.com/gillesavraam",
            "medium_avatar_url": "https://cdnb.artstation.com/p/users/avatars/002/685/317/medium/e6b8b7f8409b9bae1c59cd5cc3a2a74a.jpg?1616259212",
            "large_avatar_url": "https://cdnb.artstation.com/p/users/avatars/002/685/317/large/e6b8b7f8409b9bae1c59cd5cc3a2a74a.jpg?1616259212",
            "small_cover_url": "https://cdn.artstation.com/static_media/placeholders/user/cover/default.jpg",
            "pro_member": false
        },
        "medium": {"name": "Digital 3D", "id": 2},
        "mediums": [{"name": "Digital 3D", "id": 2}],
        "categories": [{"name": "VFX for Film, TV & Animation", "id": 64}],
        "software_items": [{
            "icon_url": "https://cdna.artstation.com/p/softwares/icons/000/000/018/default/Houdini.png?1424684347",
            "name": "Houdini"
        }],
        "id": 9601874,
        "user_id": 2685317,
        "title": "Blue fire",
        "description": "<p>Simulation de Feu r\u00e9alis\u00e9 sur houdini.</p>",
        "description_html": "<p>Simulation de Feu r\u00e9alis\u00e9 sur houdini.</p>",
        "created_at": "2021-03-20T11:44:51.286-05:00",
        "updated_at": "2021-05-11T06:27:00.043-05:00",
        "views_count": 35,
        "likes_count": 3,
        "comments_count": 0,
        "permalink": "https://www.artstation.com/artwork/GaYy0V",
        "cover_url": "https://cdnb.artstation.com/p/assets/covers/images/035/921/151/medium/gilles-avraam-gilles-avraam-post1-insta-00-00-03-00-still001.jpg?1616258688",
        "published_at": "2021-03-20T11:44:51.269-05:00",
        "editor_pick": false,
        "adult_content": false,
        "admin_adult_content": false,
        "slug": "blue-fire-10",
        "suppressed": false,
        "hash_id": "GaYy0V",
        "visible": true
    })
}